# BookBuddy Project Configuration

project:
  name: 'BookBuddy'
  description: 'A platform connecting book donors with readers'
  version: '1.0.0'

# Coding style preferences
style:
  indentation: 2
  quotes: single
  componentNaming: PascalCase
  methodNaming: camelCase

# Feature priorities and roadmap
features:
  current:
    - name: 'Enable smooth scrolling'
      priority: medium
  planned:
    - name: 'Book Request System'
      priority: medium
    - name: 'Add font size styles where missing'
      priority: medium
    - name: 'Combine modal styles into one component'
      description: 'Arguments are passed to this component. The title and other common fields are in text form and the content field is written in markup.'
      priority: medium
    - name: 'Messaging System'
      description: 'Send email notification to donor when their book is requested.'
      priority: medium
    - name: 'User Rating System'
      priority: low
    - name: 'Accessible styles'
      description: 'Use prefers-color-scheme, disable animation if browser settings request so, etc.'
      priority: medium
    - name: 'User Profile Page'
      description: 'Show user profile with their books and requests.'
      priority: low

# Architecture decisions
architecture:
  stateManagement: 'Vue Composition API'
  dataFlow: 'Top-down props'
  apiPattern: 'Service modules'

# Security rules
security:
  firestore:
    - 'Only authenticated users can create or update books'
    - 'Requests can only be created by authenticated users'
    - 'Donors can approve or reject requests'
    - 'Default deny all other access'
